### ISSUE TITLE
advanced spend builder

### ISSUE THREAD

**Issue by isaacvr** [fibercrypto/skycoin#864]
# Motivation
Allow the user to tweak his `coin hours`  and `unspents` in a transaction

# Info
- By default in a transaction, a user loses `75%` coin hours wherein `50%` is burned and `25%` is sent to destination addrs.
- The default strategy to select unspents priority is `Max skycoins` > `zero coin hours` > `non-zero coin hours` 

# Tasks
- [x] choose coin hours to be sent to destination addrs
- [x]  choose unspents to be used
- [x]  send from multiple addresses
- [x]  create `advancedCreateRawTx` command
- [x] Update changelog
- [x] Document use cases
- [ ] Tests 

# Use Cases
- This will allow users to send the desired number of coinhours to the receiver.
- Select unspent with lower coin hours to decrease transaction fees and hence preserving coinhours
